### ISSUE TITLE
Logic error in treasure vault medallions

### ISSUE THREAD

**Issue by Buccket** [TRPG0/ArchipelagoHylics2#1]
Genned a singleplayer seed with these settings:
  progression_balancing: 35
  accessibility: locations
  party_shuffle: 'true'
  gesture_shuffle: tvs_only
  medallion_shuffle: 'true'
  random_start: 'true'
  extra_items_in_logic: 'false'
  death_link: 'false'
According to a hint Pneumataphore is on a red medallion in the treasure vault, which shouldn't be logical since Pneumataphore is needed to enter the Foglast fortress and release Gibby, which would then allow access to the treasure vault.

The hint:
Notice (Team #1): [Hint]: croncrete's PNEUMATOPHORE is at New Muldul: Vault Front Left Medallion in croncrete's World.

**Comment by TRPG0** [comment]
Ah, you're right. Will open a pull request to fix that

**Comment by TRPG0** [comment]
Fixed in 0.4.6
