### ISSUE TITLE
Server crash with conflicting settings Gesture Shuffle and Extra Items

### ISSUE THREAD

**Issue by Buccket** [TRPG0/ArchipelagoHylics2#2]
Servers fail to start when the setting Gesture Shuffle is set to TVs only and the setting Extra Items is enabled. I assume its unable to find a place to put the extra Charge Up since all the other TVs are assigned to the regular Gestures. Maybe the extra Charge Up should be an exception to the TV only Gesture Shuffle setting, or maybe it simply shouldn't be added to the pool with TV only Gesture Shuffle enabled.

**Comment by TRPG0** [comment]
Which version are you generating on? This was fixed in 0.4.5

**Comment by Buccket** [comment]
ah, assuming youre referring to the archipelago version im on 0.4.4, my bad
